### ISSUE TITLE
Tracking Issue

### ISSUE THREAD

**Issue by allenlee820202** [allenlee820202/blog#1]
- [ ]  Design data schema for Articles, Users 
- [ ]  Render articles onto ```index.html``` based on Thymeleaf
- [ ]  Create Article editing page
